# Basics

In [1]:
import tensorflow as tf

### 0-D tensor

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


### 1-D tensor

In [3]:
tensor_one_d = tf.constant([5, 6, -2])
print(tensor_one_d)

tf.Tensor([ 5  6 -2], shape=(3,), dtype=int32)


In [4]:
tensor_one_d = tf.constant([5, 6, -2.])
print('tensor_one_d:\t', tensor_one_d)
print('tensor_one_d.shape:\t', tensor_one_d.shape)
print('tensor_one_d.ndim:\t',tensor_one_d.ndim)

tensor_one_d:	 tf.Tensor([ 5.  6. -2.], shape=(3,), dtype=float32)
tensor_one_d.shape:	 (3,)
tensor_one_d.ndim:	 1


### 2-D tensor

In [5]:
tensor_two_d = tf.constant([
    [5, 6, -8.],
    [1, 3, -2.]
], tf.float32)
print('tensor_two_d:\t', tensor_two_d)
print('tensor_two_d.shape:\t', tensor_two_d.shape)
print('tensor_two_d.ndim:\t',tensor_two_d.ndim)

tensor_two_d:	 tf.Tensor(
[[ 5.  6. -8.]
 [ 1.  3. -2.]], shape=(2, 3), dtype=float32)
tensor_two_d.shape:	 (2, 3)
tensor_two_d.ndim:	 2


In [6]:
tensor_two_d = tf.constant([
    [5, 6, -8],
    [1, 3, -2]
], tf.float64)
print('tensor_two_d:\t', tensor_two_d)
print('tensor_two_d.shape:\t', tensor_two_d.shape)
print('tensor_two_d.ndim:\t',tensor_two_d.ndim)

tensor_two_d:	 tf.Tensor(
[[ 5.  6. -8.]
 [ 1.  3. -2.]], shape=(2, 3), dtype=float64)
tensor_two_d.shape:	 (2, 3)
tensor_two_d.ndim:	 2


### 3-D tensor

In [7]:
tensor_three_d = tf.constant([
    [[5, 6, -8],
    [1, 3, -2]],

    [[5, 6, -8],
    [1, 3, -2]],

    [[5, 6, -8],
    [1, 3, -2]],

    [[5, 6, -8],
    [1, 3, -2]]
])
print('tensor_three_d:\t', tensor_three_d)
print('tensor_three_d.shape:\t', tensor_three_d.shape)
print('tensor_three_d.ndim:\t',tensor_three_d.ndim)

tensor_three_d:	 tf.Tensor(
[[[ 5  6 -8]
  [ 1  3 -2]]

 [[ 5  6 -8]
  [ 1  3 -2]]

 [[ 5  6 -8]
  [ 1  3 -2]]

 [[ 5  6 -8]
  [ 1  3 -2]]], shape=(4, 2, 3), dtype=int32)
tensor_three_d.shape:	 (4, 2, 3)
tensor_three_d.ndim:	 3


### 4-D tensor

In [8]:
tensor_four_d = tf.constant([
    [[[5, 6, -8],
    [1, 3, -2]],

    [[5, 6, -8],
    [1, 3, -2]],

    [[5, 6, -8],
    [1, 3, -2]],

    [[5, 6, -8],
    [1, 3, -2]]],

    [[[5, 6, -8],
    [1, 3, -2]],

    [[5, 6, -8],
    [1, 3, -2]],

    [[5, 6, -8],
    [1, 3, -2]],

    [[5, 6, -8],
    [1, 3, -2]]]
])
print('tensor_four_d:\t', tensor_four_d)
print('tensor_four_d.shape:\t', tensor_four_d.shape)
print('tensor_four_d.ndim:\t',tensor_four_d.ndim)

tensor_four_d:	 tf.Tensor(
[[[[ 5  6 -8]
   [ 1  3 -2]]

  [[ 5  6 -8]
   [ 1  3 -2]]

  [[ 5  6 -8]
   [ 1  3 -2]]

  [[ 5  6 -8]
   [ 1  3 -2]]]


 [[[ 5  6 -8]
   [ 1  3 -2]]

  [[ 5  6 -8]
   [ 1  3 -2]]

  [[ 5  6 -8]
   [ 1  3 -2]]

  [[ 5  6 -8]
   [ 1  3 -2]]]], shape=(2, 4, 2, 3), dtype=int32)
tensor_four_d.shape:	 (2, 4, 2, 3)
tensor_four_d.ndim:	 4


### Casting

In [9]:
print(tensor_one_d.dtype)

<dtype: 'float32'>


In [10]:
casted_tensor_one_d = tf.cast(tensor_one_d, tf.int64)
print('casted_tensor_one_d:\t', casted_tensor_one_d)

casted_tensor_one_d:	 tf.Tensor([ 5  6 -2], shape=(3,), dtype=int64)


In [11]:
casted_tensor_one_d = tf.cast(tensor_one_d, tf.bool)
print('casted_tensor_one_d:\t', casted_tensor_one_d)

casted_tensor_one_d:	 tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [12]:
casted_tensor_one_d = tf.cast(tf.constant([1,0,2,-1]), tf.bool)
print('casted_tensor_one_d:\t', casted_tensor_one_d)

casted_tensor_one_d:	 tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


### Convert Numpy to tensor

In [13]:
import numpy as np

In [14]:
np_arr = np.array([5,9,-2,1])
print('np_arr:\t', np_arr)

np_arr:	 [ 5  9 -2  1]


In [15]:
converted_from_numpy_array = tf.convert_to_tensor(np_arr)
print('converted_from_numpy_array:\t', converted_from_numpy_array)

converted_from_numpy_array:	 tf.Tensor([ 5  9 -2  1], shape=(4,), dtype=int32)


In [16]:
converted_from_numpy_array = tf.convert_to_tensor(np_arr, dtype = tf.float16)
print('converted_from_numpy_array:\t', converted_from_numpy_array)

converted_from_numpy_array:	 tf.Tensor([ 5.  9. -2.  1.], shape=(4,), dtype=float16)


### eye

In [17]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print('eye:\t', eye_tensor)

eye:	 tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [18]:
eye_tensor2 = tf.eye(
    num_rows = 4,
    num_columns=6,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print('eye:\t', eye_tensor2)

eye:	 tf.Tensor(
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]], shape=(4, 6), dtype=float32)


In [19]:
eye_tensor3 = tf.eye(
    num_rows = 4,
    num_columns=6,
    batch_shape=[3,2,],
    dtype=tf.dtypes.float32,
    name=None
)
print('eye:\t', eye_tensor3)

eye:	 tf.Tensor(
[[[[1. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0.]]]


 [[[1. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0.]]]


 [[[1. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0.]]]], shape=(3, 2, 4, 6), dtype=float32)


### fill

In [20]:
fill_tensor = tf.fill(
    [2, 5], 60, name=None
)
print('fill_tensor:\t', fill_tensor)

fill_tensor:	 tf.Tensor(
[[60 60 60 60 60]
 [60 60 60 60 60]], shape=(2, 5), dtype=int32)


In [21]:
fill_tensor2 = tf.fill(
    [2, 5], 1, name=None
)
print('fill_tensor2:\t', fill_tensor2)

fill_tensor2:	 tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]], shape=(2, 5), dtype=int32)


In [22]:
fill_tensor3 = tf.fill(
    [2, 5], 1., name=None
)
print('fill_tensor3:\t', fill_tensor3)

fill_tensor3:	 tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(2, 5), dtype=float32)


### ones

In [23]:
ones_tensor = tf.ones([2,5])
print('ones_tensor:\t', ones_tensor)

ones_tensor:	 tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(2, 5), dtype=float32)


In [24]:
ones_tensor = tf.ones([2,5], dtype= tf.int16)
print('ones_tensor:\t', ones_tensor)

ones_tensor:	 tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]], shape=(2, 5), dtype=int16)


### ones like

In [25]:
ones_like_tensor = tf.ones_like(fill_tensor)
print('ones_like_tensor:\t', ones_like_tensor)

ones_like_tensor:	 tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]], shape=(2, 5), dtype=int32)


In [26]:
ones_like_tensor2 = tf.ones_like([10,20,0])
print('ones_like_tensor2:\t', ones_like_tensor2)

ones_like_tensor2:	 tf.Tensor([1 1 1], shape=(3,), dtype=int32)


In [27]:
ones_like_tensor3 = 2*tf.ones_like([10,20,0])
print('ones_like_tensor3:\t', ones_like_tensor3)

ones_like_tensor3:	 tf.Tensor([2 2 2], shape=(3,), dtype=int32)


In [28]:
print(ones_like_tensor3.ndim)

1


### zeros and zeros_like

In [29]:
zeros_tensor = tf.zeros([2,5])
print('zeros_tensor:\t', zeros_tensor)

zeros_tensor:	 tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(2, 5), dtype=float32)


In [30]:
zeros_tensor2 = tf.zeros([2,5], dtype=tf.int32)
print('zeros_tensor2:\t', zeros_tensor2)

zeros_tensor2:	 tf.Tensor(
[[0 0 0 0 0]
 [0 0 0 0 0]], shape=(2, 5), dtype=int32)


In [31]:
zeros_like_tensor = tf.zeros_like([2,5])
print('zeros_like_tensor:\t', zeros_like_tensor)

zeros_like_tensor:	 tf.Tensor([0 0], shape=(2,), dtype=int32)


In [32]:
zeros_like_tensor = tf.zeros_like([2.,5])
print('zeros_like_tensor:\t', zeros_like_tensor)

zeros_like_tensor:	 tf.Tensor([0. 0.], shape=(2,), dtype=float32)


### rank

In [33]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
print(tf.rank(t))  # 3

tf.Tensor(3, shape=(), dtype=int32)


### size
#### the number of elements

In [34]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
print(tf.size(t))


tf.Tensor(12, shape=(), dtype=int32)


In [35]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
print(tf.size(t, out_type = tf.float16))

tf.Tensor(12.0, shape=(), dtype=float16)


## tf.random.normal

In [36]:
normal_tensor = tf.random.normal(
    shape = [1,2],
    mean=0.0,
    stddev=2.0,
    dtype=tf.dtypes.float32,
)
print("normal_tensor:\t", normal_tensor)

normal_tensor:	 tf.Tensor([[1.6857936 1.651685 ]], shape=(1, 2), dtype=float32)


## tf.random.uniform

In [37]:
uniform_tensor = tf.random.uniform(
    shape = (10, 1),
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
)
print("uniform_tensor:\t", uniform_tensor)

uniform_tensor:	 tf.Tensor(
[[0.12703407]
 [0.6158823 ]
 [0.23219073]
 [0.4852581 ]
 [0.86816776]
 [0.17357564]
 [0.41343486]
 [0.4297861 ]
 [0.75191784]
 [0.5152308 ]], shape=(10, 1), dtype=float32)


In [38]:
uniform_tensor2 = tf.random.uniform(
    shape = (10, 1),
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
)
print("uniform_tensor2:\t", uniform_tensor2)

uniform_tensor2:	 tf.Tensor(
[[63.64746  ]
 [ 1.5659928]
 [72.42453  ]
 [43.041492 ]
 [87.64807  ]
 [57.346107 ]
 [31.83856  ]
 [92.69754  ]
 [31.860077 ]
 [ 9.259796 ]], shape=(10, 1), dtype=float32)


In [39]:
uniform_tensor3 = tf.random.uniform(
    shape = (10, 3),
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
)
print("uniform_tensor3:\t", uniform_tensor3)

uniform_tensor3:	 tf.Tensor(
[[752 909 177]
 [836 341 437]
 [352 470 253]
 [251 907   5]
 [713 544 116]
 [249 609 994]
 [126 164 823]
 [798 681 918]
 [634 283 478]
 [ 50 185 889]], shape=(10, 3), dtype=int32)


## Seed

In [40]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))

tf.Tensor(70, shape=(), dtype=int32)
tf.Tensor(97, shape=(), dtype=int32)
tf.Tensor(99, shape=(), dtype=int32)
tf.Tensor(63, shape=(), dtype=int32)
tf.Tensor(62, shape=(), dtype=int32)
tf.Tensor(41, shape=(), dtype=int32)


In [41]:
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))
print(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(64, shape=(), dtype=int32)
tf.Tensor(88, shape=(), dtype=int32)
tf.Tensor(35, shape=(), dtype=int32)
tf.Tensor(85, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
