In [1]:
import tensorflow as tf
import numpy as np

# Indexing

In [2]:
constant_tensor = tf.constant([1, 2, 3, 4, 5, 6])
print("constant_tensor:\t", constant_tensor)

constant_tensor:	 tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [3]:
constant_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
constant_tensor[2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
constant_tensor[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [6]:
constant_tensor2 = tf.constant([[1, 2, 3, 4, 5, 6],[7,8,9,10,11,12]])
print("constant_tensor2:\t", constant_tensor2)

constant_tensor2:	 tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)


In [7]:
constant_tensor2[:1]

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]])>

In [8]:
constant_tensor2[:1,:-4]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

In [9]:
constant_tensor2[...,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>

In [10]:
constant_tensor3 = tf.constant([[[1, 2, 3, 4, 5, 6],[7,8,9,10,11,12], [13,14,15,16,17,18]]])
print("constant_tensor3:\t", constant_tensor3)

constant_tensor3:	 tf.Tensor(
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]], shape=(1, 3, 6), dtype=int32)


In [11]:
constant_tensor3[...,:2,0]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 7]])>

In [12]:
constant_tensor3[...,0]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 1,  7, 13]])>

# Math Operations

## abs

In [13]:
abss = tf.abs(tf.constant([1, -12, -53, 4, 5, 6]))
print("abss:\t", abss)

abss:	 tf.Tensor([ 1 12 53  4  5  6], shape=(6,), dtype=int32)


In [14]:
complexe = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
print("complexe:\t", complexe)

complexe:	 tf.Tensor(
[[-2.25+4.75j]
 [-3.25+5.75j]], shape=(2, 1), dtype=complex128)


In [15]:
print("complexe abs:\t", tf.abs(complexe))

complexe abs:	 tf.Tensor(
[[5.25594901]
 [6.60492241]], shape=(2, 1), dtype=float64)


## With math

In [16]:
abss = tf.math.abs(tf.constant([1, -12, -53, 4, 5, 6]))
print("abss:\t", abss)

abss:	 tf.Tensor([ 1 12 53  4  5  6], shape=(6,), dtype=int32)


## acos

In [17]:
x = tf.constant([1.0, -0.5, 3.4, 0.2, 0.0, -2], dtype = tf.float32)
acos_tensor = tf.math.acos(x)
print("acos_tensor:\t", acos_tensor)

acos_tensor:	 tf.Tensor([0.        2.0943952       nan 1.3694383 1.5707964       nan], shape=(6,), dtype=float32)


## divide

In [18]:
x = tf.constant([16, 12, 11])
y = tf.constant([4, 6, 2])
print('Divide:\t', tf.divide(x,y))

Divide:	 tf.Tensor([4.  2.  5.5], shape=(3,), dtype=float64)


In [19]:
x = tf.constant([16, 12, 11])
y = tf.constant([4, 0, 2])
print('Divide:\t', tf.divide(x,y))

Divide:	 tf.Tensor([4.  inf 5.5], shape=(3,), dtype=float64)


## divide_no_nan

In [20]:
print('divide_no_nan:\t', tf.math.divide_no_nan(x,y))

divide_no_nan:	 tf.Tensor([4.  0.  5.5], shape=(3,), dtype=float64)


In [21]:
x = tf.constant([16, 12, 11], dtype = tf.int32)
y = tf.constant([4, 0, 2], dtype = tf.int32)
print('divide_no_nan:\t', tf.math.divide_no_nan(x,y))

divide_no_nan:	 tf.Tensor([4.  0.  5.5], shape=(3,), dtype=float64)


## add

In [22]:
x = [1, 2, 3, 4, 5]
y = 1
print("add:\t", tf.add(x, y))

add:	 tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)


In [23]:
x = [1, 2, 3, 4, 5]
y = tf.constant([1, 2, 3, 4, 5])
print("add:\t", tf.add(x, y))

add:	 tf.Tensor([ 2  4  6  8 10], shape=(5,), dtype=int32)


In [24]:
x = tf.constant([1, 2], dtype=tf.int8)
y = [2**7 + 1, 2**7 + 2]
print("add:\t", tf.add(x, y))

add:	 tf.Tensor([-126 -124], shape=(2,), dtype=int8)


In [25]:
x = np.ones(6).reshape(1, 2, 1, 3)
y = np.ones(6).reshape(2, 1, 3, 1)
print("add:\t", tf.add(x, y).shape.as_list())

add:	 [2, 2, 3, 3]


In [26]:
x

array([[[[1., 1., 1.]],

        [[1., 1., 1.]]]])

In [27]:
y

array([[[[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]]]])

In [28]:
x = tf.constant([1,2,9], dtype=tf.int8)
y = tf.constant([1, 2,4], dtype=tf.int8)
print("add:\t", tf.add(x, y))

add:	 tf.Tensor([ 2  4 13], shape=(3,), dtype=int8)


In [29]:
x = tf.constant([1,2,9], dtype=tf.int8)
y = tf.constant([[2], [4], [8]], dtype=tf.int8)
print("add:\t", tf.add(x, y))

add:	 tf.Tensor(
[[ 3  4 11]
 [ 5  6 13]
 [ 9 10 17]], shape=(3, 3), dtype=int8)


## add_in
## This op does not broadcast its inputs.

In [30]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print("add_n:\t", tf.math.add_n([a,b]))

add_n:	 tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [31]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print("add_n:\t", tf.math.add_n(a,b))

add_n:	 tf.Tensor([ 7 13], shape=(2,), dtype=int32)


## argmax

In [32]:
A = tf.constant([2, 20, 30, 3, 6])
print("argmax:\t", tf.math.argmax(A)) 

argmax:	 tf.Tensor(2, shape=(), dtype=int64)


In [33]:
A = tf.constant([[2, 20, 30, 3, 6], [4, 3, 50, 60, 1]])
print("argmax:\t", tf.math.argmax(A)) 

argmax:	 tf.Tensor([1 0 1 1 0], shape=(5,), dtype=int64)


In [34]:
A = tf.constant([[2, 20, 30, 3, 6], [4, 3, 50, 60, 1]])
print("argmax:\t", tf.math.argmax(A, axis = 0)) 

argmax:	 tf.Tensor([1 0 1 1 0], shape=(5,), dtype=int64)


In [35]:
A = tf.constant([[2, 20, 30, 3, 6], [4, 3, 50, 60, 1]])
print("argmax:\t", tf.math.argmax(A, axis = 1)) 

argmax:	 tf.Tensor([2 3], shape=(2,), dtype=int64)


## ceil

In [36]:
x = tf.constant([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print("ceil:\t", tf.math.ceil(x))

ceil:	 tf.Tensor([-1. -1.  0.  1.  2.  2.  2.], shape=(7,), dtype=float32)


## floor

In [37]:
x = tf.constant([1.3324, -1.5, 5.555, -2.532, 0.99, float("inf")])
print("floor:\t", tf.floor(x).numpy())

floor:	 [ 1. -2.  5. -3.  0. inf]


## floordiv

In [38]:
x = tf.constant([10,20,30])
y = tf.constant([40,-1,60])
print("floordiv:\t", tf.math.floordiv(x, y))

floordiv:	 tf.Tensor([  0 -20   0], shape=(3,), dtype=int32)


## multiply

In [39]:
x = tf.constant([1,2,9], dtype=tf.int8)
y = tf.constant([[2], [4], [8]], dtype=tf.int8)
print("add:\t", tf.multiply(x, y))

add:	 tf.Tensor(
[[ 2  4 18]
 [ 4  8 36]
 [ 8 16 72]], shape=(3, 3), dtype=int8)


## confusion_matrix

In [40]:
tf.math.confusion_matrix([1, 2, 4], [2, 2, 4]) 

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]])>

## count non zeros

In [41]:
x = tf.constant([[0, 1, 0], [1, 1, 0]])
print(tf.math.count_nonzero(x))
print(tf.math.count_nonzero(x, 0))
print(tf.math.count_nonzero(x, 1))
print(tf.math.count_nonzero(x, 1, keepdims=True))
print(tf.math.count_nonzero(x, [0, 1]))

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([1 2 0], shape=(3,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


## equal

In [42]:
x = tf.constant([2, 4])
y = tf.constant(2)
print("equal: \t", tf.math.equal(x, y))

equal: 	 tf.Tensor([ True False], shape=(2,), dtype=bool)


In [43]:
x = tf.constant([[2, 4], [8, 2]])
y = tf.constant(2)
print("equal: \t", tf.math.equal(x, y))

equal: 	 tf.Tensor(
[[ True False]
 [False  True]], shape=(2, 2), dtype=bool)


In [44]:
x = tf.constant([[2, 4], [8, 2]])
y = tf.constant([2, 3])
print("equal: \t", tf.math.equal(x, y))

equal: 	 tf.Tensor(
[[ True False]
 [False False]], shape=(2, 2), dtype=bool)


## exp

In [45]:
x = tf.constant(2.0)
print("exp:\t", tf.math.exp(x))

exp:	 tf.Tensor(7.389056, shape=(), dtype=float32)


In [46]:
x = tf.constant([5,9,-1], dtype = tf.float32)
print("exp:\t", tf.math.exp(x))

exp:	 tf.Tensor([1.4841316e+02 8.1030840e+03 3.6787945e-01], shape=(3,), dtype=float32)


## greater

In [47]:
x = tf.constant([5, 4, 6])
y = tf.constant([5, 2, 5])
print("greater:\t", tf.math.greater(x, y))

greater:	 tf.Tensor([False  True  True], shape=(3,), dtype=bool)


## greater_equal

In [48]:
x = tf.constant([5, 4, 6, 7])
y = tf.constant([5, 2, 5, 10])
print("greater:\t", tf.math.greater_equal(x, y))

greater:	 tf.Tensor([ True  True  True False], shape=(4,), dtype=bool)


## maximum

In [49]:
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5.])
print("maximun:\t", tf.math.maximum(x, y))

maximun:	 tf.Tensor([0. 0. 2. 5.], shape=(4,), dtype=float32)


In [50]:
x = tf.constant([-6.])
y = tf.constant([-2., 0., 2., 5.])
print("maximun:\t", tf.math.maximum(x, y))

maximun:	 tf.Tensor([-2.  0.  2.  5.], shape=(4,), dtype=float32)


## negative

In [51]:
tf.math.negative(-6.)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [52]:
tf.math.negative(6.)

<tf.Tensor: shape=(), dtype=float32, numpy=-6.0>

## reduce_max

In [53]:
x = tf.constant([5, 1, 2, 4])
print("reduce_max:\t", tf.reduce_max(x))

reduce_max:	 tf.Tensor(5, shape=(), dtype=int32)


## reduce_min

In [54]:
x = tf.constant([5, 1, 2, 4])
print("reduce_min:\t", tf.reduce_min(x))

reduce_min:	 tf.Tensor(1, shape=(), dtype=int32)


## Sigmoid

In [55]:
x = tf.constant([0.0, 1.0, 50.0, 100.0])
print("sigmpid:\t", tf.math.sigmoid(x))

sigmpid:	 tf.Tensor([0.5       0.7310586 1.        1.       ], shape=(4,), dtype=float32)


## Top_K

In [56]:
top_three = tf.math.top_k([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
                       k=3)
print("top_three:\t", top_three)

top_three:	 TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 1])>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 3])>)


In [57]:
top_three = tf.math.top_k([[1,2,3,30],[12,13,15,2],[60,15,48,12]],
                       k=3)
print("top_three:\t", top_three)

top_three:	 TopKV2(values=<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[30,  3,  2],
       [15, 13, 12],
       [60, 48, 15]])>, indices=<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 2, 1],
       [2, 1, 0],
       [0, 2, 1]])>)


In [58]:
top_three = tf.math.top_k([[1,2,3,30],[12,13,15,2],[60,15,48,12]],
                       k=3, sorted = False)
print("top_three:\t", top_three)

top_three:	 TopKV2(values=<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2, 30,  3],
       [12, 13, 15],
       [15, 60, 48]])>, indices=<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 3, 2],
       [0, 1, 2],
       [1, 0, 2]])>)


In [59]:
top_one = tf.math.top_k([[10,-3,9],[-8,6,2]],
                       k=1)
print("top_one:\t", top_one)

top_one:	 TopKV2(values=<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [ 6]])>, indices=<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[0],
       [1]])>)


In [60]:
int(tf.Variable(top_one.values.numpy)[0])

10