In [1]:
import tensorflow as tf
import numpy as np

## linalg.matmul

# 2D

In [2]:
mat_1 = tf.constant([[3, 2, 5, 4], 
                     [23,32,55,14]])
mat_2 = tf.constant([[3, 2], 
                     [23,32], 
                     [13,12], 
                     [31,21]])

mul = tf.linalg.matmul(
      mat_1,
      mat_2,
      transpose_a=False,
      transpose_b=False,
      adjoint_a=False,
      adjoint_b=False,
      a_is_sparse=False,
      b_is_sparse=False,
      output_type=None,
      name=None
)
print("shapes: \t",mat_1.shape," X ", mat_2.shape)
print('mul: \t', mul)

shapes: 	 (2, 4)  X  (4, 2)
mul: 	 tf.Tensor(
[[ 244  214]
 [1954 2024]], shape=(2, 2), dtype=int32)


In [3]:
print("shapes: \t",mat_1.shape," X ", mat_2.shape)
print('mul: \t', mat_1 @ mat_2)

shapes: 	 (2, 4)  X  (4, 2)
mul: 	 tf.Tensor(
[[ 244  214]
 [1954 2024]], shape=(2, 2), dtype=int32)


In [4]:
mul2 = tf.linalg.matmul(mat_2, mat_1)
print("shapes: \t",mat_2.shape," X ", mat_1.shape)
print('mul: \t', mul2)

shapes: 	 (4, 2)  X  (2, 4)
mul: 	 tf.Tensor(
[[  55   70  125   40]
 [ 805 1070 1875  540]
 [ 315  410  725  220]
 [ 576  734 1310  418]], shape=(4, 4), dtype=int32)


In [5]:
print("shapes: \t",mat_2.shape," X ", mat_1.shape)
print('mul: \t', mat_2 @ mat_1)

shapes: 	 (4, 2)  X  (2, 4)
mul: 	 tf.Tensor(
[[  55   70  125   40]
 [ 805 1070 1875  540]
 [ 315  410  725  220]
 [ 576  734 1310  418]], shape=(4, 4), dtype=int32)


In [6]:
mat_1 = tf.constant([[3, 2, 5, 4], 
                     [23,32,55,14]])
mat_2 = tf.constant([[3, 2], 
                     [23,32], 
                     [13,12], 
                     [31,21]])
mul = tf.linalg.matmul(mat_1, mat_2)
print("shapes: \t",mat_1.shape," X ", mat_2.shape)
print('mul: \t', mul)

shapes: 	 (2, 4)  X  (4, 2)
mul: 	 tf.Tensor(
[[ 244  214]
 [1954 2024]], shape=(2, 2), dtype=int32)


# 3D

In [7]:
mat_1 = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])
mat_2 = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])

mul = tf.linalg.matmul(
      mat_1,
      mat_2,
      transpose_a=False,
      transpose_b=False,
      adjoint_a=False,
      adjoint_b=False,
      a_is_sparse=False,
      b_is_sparse=False,
      output_type=None,
      name=None
)
print("mat_1:\t",mat_1)
print("mat_2:\t",mat_2)
print("shapes: \t",mat_1.shape," X ", mat_2.shape)
print('mul: \t', mul)

mat_1:	 tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
mat_2:	 tf.Tensor(
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]], shape=(2, 3, 2), dtype=int32)
shapes: 	 (2, 2, 3)  X  (2, 3, 2)
mul: 	 tf.Tensor(
[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]], shape=(2, 2, 2), dtype=int32)


In [8]:
mat_1 = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])
mat_2 = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])

mul = mat_1 @ mat_2
print("mat_1:\t",mat_1)
print("mat_2:\t",mat_2)
print("shapes: \t",mat_1.shape," X ", mat_2.shape)
print('mul: \t', mul)

mat_1:	 tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
mat_2:	 tf.Tensor(
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]], shape=(2, 3, 2), dtype=int32)
shapes: 	 (2, 2, 3)  X  (2, 3, 2)
mul: 	 tf.Tensor(
[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]], shape=(2, 2, 2), dtype=int32)


# tf.transpose()

In [9]:
mat_1 = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 3, 2])
mat_2 = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])

mul = tf.linalg.matmul(
      mat_1,
      mat_2,
      transpose_a=False,
      transpose_b=False,
      adjoint_a=False,
      adjoint_b=False,
      a_is_sparse=False,
      b_is_sparse=False,
      output_type=None,
      name=None
)
print("mat_1:\t",mat_1)
print("mat_2:\t",mat_2)
print("shapes: \t",mat_1.shape," X ", mat_2.shape)
print('mul: \t', mul)

InvalidArgumentError: {{function_node __wrapped__BatchMatMulV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3,2], In[1]: [2,3,2] [Op:BatchMatMulV2] name: 

In [ ]:
mat_1 = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 3, 2])
mat_2 = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])


mul = tf.linalg.matmul(
      mat_1,
      mat_2,
      transpose_a=True,
      transpose_b=False,
      adjoint_a=False,
      adjoint_b=False,
      a_is_sparse=False,
      b_is_sparse=False,
      output_type=None,
      name=None
)
print("mat_1:\t",mat_1)
print("mat_2:\t",mat_2)
print("shapes: \t",mat_1.shape," X ", mat_2.shape)
print('mul: \t', mul)

In [ ]:
mat_3 = tf.transpose(mat_2)
print("mat_3:\t", mat_3)

# 4D

In [ ]:
mat_1 = tf.constant(np.arange(1, 37, dtype=np.int32), shape=[2, 3, 2,3])
mat_2 = tf.constant(np.arange(37, 73, dtype=np.int32), shape=[2, 3, 3,2])


mul = tf.linalg.matmul(
      mat_1,
      mat_2,
      transpose_a=False,
      transpose_b=False,
      adjoint_a=False,
      adjoint_b=False,
      a_is_sparse=False,
      b_is_sparse=False,
      output_type=None,
      name=None
)
print("mat_1:\t",mat_1)
print("mat_2:\t",mat_2)
print("shapes: \t",mat_1.shape," X ", mat_2.shape)
print('mul: \t', mul)

# band_part

In [10]:
mat = tf.constant([[ 0,  1,  2, 3],
                   [-1,  5,  1, 2],
                   [-2, -1,  5, 1],
                   [-3, -2, -1, 0]], dtype = tf.int32)
mat

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [-1,  5,  1,  2],
       [-2, -1,  5,  1],
       [-3, -2, -1,  0]])>

In [11]:
l = -1 #If negative, keep entire lower triangle.
u = -1 # If negative, keep entire upper triangle.
tf.linalg.band_part(mat, l, u) 

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [-1,  5,  1,  2],
       [-2, -1,  5,  1],
       [-3, -2, -1,  0]])>

In [12]:
l = 0 # 0 Number of subdiagonals to keep in lower
u = 0 # 0 Number of subdiagonals to keep in upper
# if both l and u are zeros it will be diagonal matrix
tf.linalg.band_part(mat, l, u) 

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 0]])>

In [13]:
l = 1 # 0 Number of subdiagonals to keep in lower
u = 0 # 0 Number of subdiagonals to keep in upper
tf.linalg.band_part(mat, l, u) 

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  0,  0,  0],
       [-1,  5,  0,  0],
       [ 0, -1,  5,  0],
       [ 0,  0, -1,  0]])>

In [14]:
l = 1 # 0 Number of subdiagonals to keep in lower
u = 2 # 0 Number of subdiagonals to keep in upper
tf.linalg.band_part(mat, l, u) 

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  0],
       [-1,  5,  1,  2],
       [ 0, -1,  5,  1],
       [ 0,  0, -1,  0]])>

In [15]:
l = 1 # 0 Number of subdiagonals to keep in lower
u = 1 # 0 Number of subdiagonals to keep in upper
tf.linalg.band_part(mat, l, u) 

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  0,  0],
       [-1,  5,  1,  0],
       [ 0, -1,  5,  1],
       [ 0,  0, -1,  0]])>

# inv

In [16]:
mat_1 = tf.constant([[12, 3],
                   [15, 5]], dtype = tf.float32)
result = tf.linalg.inv(
    mat_1, adjoint=True, name=None
)
print(result)

tf.Tensor(
[[ 0.33333334 -1.        ]
 [-0.2         0.8       ]], shape=(2, 2), dtype=float32)


In [17]:
tf.round(tf.linalg.inv(
    result, adjoint=True, name=None
))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[12.,  3.],
       [15.,  5.]], dtype=float32)>

# svd

In [18]:
s, u, v = tf.linalg.svd(mat_1)
print("mat_1:\t", mat_1)
print("\nS:\t", s)
print("\nU:\t", u)
print("\nV:\t", v)

mat_1:	 tf.Tensor(
[[12.  3.]
 [15.  5.]], shape=(2, 2), dtype=float32)

S:	 tf.Tensor([20.060928  0.747722], shape=(2,), dtype=float32)

U:	 tf.Tensor(
[[ 0.61588776 -0.78783387]
 [ 0.78783387  0.61588776]], shape=(2, 2), dtype=float32)

V:	 tf.Tensor(
[[ 0.9574911  -0.28846282]
 [ 0.28846282  0.9574911 ]], shape=(2, 2), dtype=float32)


In [19]:
a = np.array([[1, 2,3], [5,5, 6]])
print(a.shape)
b = np.array([[2, 6], [6, 2]])
print(b.shape)
np.einsum("ij,jk -> ik",a.T,b).shape

(2, 3)
(2, 2)


(3, 2)

In [20]:
a = np.random.randn(2, 4, 4, 2)
b = np.random.randn(2, 4, 4, 2)
np.einsum("abcd,abce -> abce",a,b).shape

(2, 4, 4, 2)

In [21]:
mat = tf.constant([[1, 3], 
                   [5, 7]], dtype = tf.float32)
print(mat)


tf.Tensor(
[[1. 3.]
 [5. 7.]], shape=(2, 2), dtype=float32)


# Det

In [22]:
tf.linalg.det(mat)

<tf.Tensor: shape=(), dtype=float32, numpy=-8.0>