In [1]:
import tensorflow as tf
import numpy as np

# tf.expand_dims

In [2]:
mat_1 = tf.constant([1, 2, 3])
print('mat_1:\t', mat_1)

mat_1:	 tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [3]:
expanded_mat_1 = tf.expand_dims(
    mat_1, axis=0, name=None
)
print('expanded_mat_1:\t', expanded_mat_1)

expanded_mat_1:	 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [4]:
expanded_mat_1 = tf.expand_dims(
    mat_1, axis=1, name=None
)
print('expanded_mat_1:\t', expanded_mat_1)

expanded_mat_1:	 tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [5]:
expanded_mat_1 = tf.expand_dims(mat_1, axis = 0)
print('expanded_mat_1:\t', expanded_mat_1)

expanded_mat_1:	 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [6]:
mat_2 = tf.constant([[1, 2, 3],
                    [6, 5, 2]])
print('mat_2:\t', mat_2)

mat_2:	 tf.Tensor(
[[1 2 3]
 [6 5 2]], shape=(2, 3), dtype=int32)


In [7]:
expanded_mat_2 = tf.expand_dims(mat_2, axis = 0)
print('expanded_mat_2:\t', expanded_mat_2)

expanded_mat_2:	 tf.Tensor(
[[[1 2 3]
  [6 5 2]]], shape=(1, 2, 3), dtype=int32)


In [8]:
expanded_mat_2 = tf.expand_dims(mat_2, axis = 1)
print('expanded_mat_2:\t', expanded_mat_2)

expanded_mat_2:	 tf.Tensor(
[[[1 2 3]]

 [[6 5 2]]], shape=(2, 1, 3), dtype=int32)


In [9]:
expanded_mat_2 = tf.expand_dims(mat_2, axis = 2)
print('expanded_mat_2:\t', expanded_mat_2)

expanded_mat_2:	 tf.Tensor(
[[[1]
  [2]
  [3]]

 [[6]
  [5]
  [2]]], shape=(2, 3, 1), dtype=int32)


# tf.squeeze

In [10]:
print('expanded_mat_1:\t', expanded_mat_1)

expanded_mat_1:	 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [11]:
squeezed_dim_1 =tf.squeeze(
    expanded_mat_1, axis=0, name=None
) 
print('squeezed_dim_1:\t', squeezed_dim_1)

squeezed_dim_1:	 tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [12]:
print('expanded_mat_2:\t', expanded_mat_2)

expanded_mat_2:	 tf.Tensor(
[[[1]
  [2]
  [3]]

 [[6]
  [5]
  [2]]], shape=(2, 3, 1), dtype=int32)


In [13]:
squeezed_dim_2 =tf.squeeze(
    expanded_mat_2, axis=2, name=None
) 
print('squeezed_dim_2:\t', squeezed_dim_2)

squeezed_dim_2:	 tf.Tensor(
[[1 2 3]
 [6 5 2]], shape=(2, 3), dtype=int32)


# tf.reshape

In [14]:
reshaped_dim_2 =tf.reshape(
    expanded_mat_2, shape=[2,3], name=None
) 
print('reshaped_dim_2:\t', reshaped_dim_2)

reshaped_dim_2:	 tf.Tensor(
[[1 2 3]
 [6 5 2]], shape=(2, 3), dtype=int32)


In [15]:
reshaped_dim_2 =tf.reshape(
    expanded_mat_2, shape=[3, 2], name=None
) 
print('reshaped_dim_2:\t', reshaped_dim_2)

reshaped_dim_2:	 tf.Tensor(
[[1 2]
 [3 6]
 [5 2]], shape=(3, 2), dtype=int32)


# tf.concat

In [16]:
t1 = tf.constant([[1, 2, 3], 
                  [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], 
                  [10, 11, 12]])
concanated_rows = tf.concat([t1, t2], axis = 0)
print("concanated_rows:\t", concanated_rows)

concanated_rows:	 tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [17]:
concanated_columns = tf.concat([t1, t2], axis = 1)
print("concanated_columns:\t", concanated_columns)

concanated_columns:	 tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


# tf.stack

In [18]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
stacked_0 = tf.stack([x, y, z], axis=0)
print("stacked_0:\t", stacked_0)

stacked_0:	 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [19]:
stacked_1 = tf.stack([x, y, z], axis=1)
print("stacked_1:\t", stacked_1)

stacked_1:	 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [20]:
x = tf.constant([[1, 4, 8],
                 [3, 5, 9]])
y = tf.constant([[2, 5, 3],
                [2, 5, 4]])
z = tf.constant([[3, 6, 11],
                [2, 7, 66]])
stacked_0 = tf.stack([x, y, z], axis=0)
print("stacked_0:\t", stacked_0)

stacked_0:	 tf.Tensor(
[[[ 1  4  8]
  [ 3  5  9]]

 [[ 2  5  3]
  [ 2  5  4]]

 [[ 3  6 11]
  [ 2  7 66]]], shape=(3, 2, 3), dtype=int32)


In [21]:
stacked_0 = tf.stack([x, y, z], axis=1)
print("stacked_0:\t", stacked_0)

stacked_0:	 tf.Tensor(
[[[ 1  4  8]
  [ 2  5  3]
  [ 3  6 11]]

 [[ 3  5  9]
  [ 2  5  4]
  [ 2  7 66]]], shape=(2, 3, 3), dtype=int32)


In [22]:
tf.concat([tf.expand_dims(t, axis = 0) for t in [x,y,z]], axis = 0)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  4,  8],
        [ 3,  5,  9]],

       [[ 2,  5,  3],
        [ 2,  5,  4]],

       [[ 3,  6, 11],
        [ 2,  7, 66]]])>

In [23]:
tf.concat([tf.expand_dims(t, axis = 1) for t in [x,y,z]], axis = 1)

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  4,  8],
        [ 2,  5,  3],
        [ 3,  6, 11]],

       [[ 3,  5,  9],
        [ 2,  5,  4],
        [ 2,  7, 66]]])>

In [24]:
for t in [x,y,z]: print(tf.expand_dims(t, axis = 0)) 

tf.Tensor(
[[[1 4 8]
  [3 5 9]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[2 5 3]
  [2 5 4]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[ 3  6 11]
  [ 2  7 66]]], shape=(1, 2, 3), dtype=int32)


# tf.pad

In [25]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[1, 1], # num of rows in top and num of rows in buttom
                        [2, 2]]) # num of rows in left and num of rows in right
res = tf.pad(t, paddings, "CONSTANT")

print("res:\t", res)

res:	 tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)


In [26]:
res = tf.pad(t, paddings, "CONSTANT", constant_values = 10)
print("res:\t", res)

res:	 tf.Tensor(
[[10 10 10 10 10 10 10]
 [10 10  1  2  3 10 10]
 [10 10  4  5  6 10 10]
 [10 10 10 10 10 10 10]], shape=(4, 7), dtype=int32)


In [27]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[1, 1], # num of rows in top and num of rows in buttom
                        [2, 2]]) # num of rows in left and num of rows in right

res = tf.pad(t, paddings, "REFLECT")
print("res:\t", res)

res:	 tf.Tensor(
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]], shape=(4, 7), dtype=int32)


In [28]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[1, 1], # num of rows in top and num of rows in buttom
                        [2, 2]]) # num of rows in left and num of rows in right

res = tf.pad(t, paddings, "REFLECT")
print("res:\t", res)

res:	 tf.Tensor(
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]], shape=(4, 7), dtype=int32)


In [29]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[2, 2], # num of rows in top and num of rows in buttom
                        [2, 2]]) # num of rows in left and num of rows in right

res = tf.pad(t, paddings, "SYMMETRIC")
print("res:\t", res)

res:	 tf.Tensor(
[[5 4 4 5 6 6 5]
 [2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]
 [2 1 1 2 3 3 2]], shape=(6, 7), dtype=int32)


# tf.gather

In [30]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(tf.gather(params, [0,1,2]))

tf.Tensor([b'p0' b'p1' b'p2'], shape=(3,), dtype=string)


In [31]:
print(tf.gather(params, [0,3,2]))

tf.Tensor([b'p0' b'p3' b'p2'], shape=(3,), dtype=string)


In [32]:
print(tf.gather(params, [4,2]))

tf.Tensor([b'p4' b'p2'], shape=(2,), dtype=string)


In [33]:
parames = tf.constant([[1, 2, 3],
                       [4, 5, 6]])
print(tf.gather(parames, [0, 1]))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [34]:
print(tf.gather(parames, [0,2], axis = 1))

tf.Tensor(
[[1 3]
 [4 6]], shape=(2, 2), dtype=int32)


# tf.gather_nd

In [35]:
params = tf.constant([['a', 'b'],
                      ['c', 'd'],
                      ['e', 'f']])
print("params:\t", params)

params:	 tf.Tensor(
[[b'a' b'b']
 [b'c' b'd']
 [b'e' b'f']], shape=(3, 2), dtype=string)


In [36]:
indices = [[1]]
print(tf.gather_nd(params, indices))

tf.Tensor([[b'c' b'd']], shape=(1, 2), dtype=string)


In [37]:
indices = [1]
print(tf.gather_nd(params, indices))

tf.Tensor([b'c' b'd'], shape=(2,), dtype=string)


In [38]:
indices = [[1],[2]]
print(tf.gather_nd(params, indices))

tf.Tensor(
[[b'c' b'd']
 [b'e' b'f']], shape=(2, 2), dtype=string)


In [39]:
tf.gather_nd(
    indices = [[[0, 1], [1, 0]], [[0, 0], [1, 1]]],
    params = [[['a0', 'b0'], 
               ['c0', 'd0']],
              
              [['a1', 'b1'], 
               ['c1', 'd1']]])

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>