In [1]:
import tensorflow as tf
import numpy as np

# tf.ragged.constant

In [2]:
pylist = [[1, 2, 3],
         [5],
         [8,6],
         []]
ragged_constant = tf.ragged.constant(
    pylist,
    dtype=None,
    ragged_rank=None,
    inner_shape=None,
    name=None,
    row_splits_dtype=tf.dtypes.int64
)
print("ragged_constant.shape:\t", ragged_constant.shape)
print("ragged_constant:\t", ragged_constant)

ragged_constant.shape:	 (4, None)
ragged_constant:	 <tf.RaggedTensor [[1, 2, 3], [5], [8, 6], []]>


# tf.ragged.boolean_mask

In [3]:
tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[True, False, True], [False, False, False], [True, False, False]]).to_list()

[[1, 3], [], [7]]

In [4]:
T, F = (True, False)

tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[T, F, T], [F, F, F], [T, F, F]])

<tf.RaggedTensor [[1, 3], [], [7]]>

In [5]:
T, F = (True, False)

tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[T, F, T], [F, F, F], [T, F, F]]).to_list()

[[1, 3], [], [7]]

In [6]:
tf.ragged.boolean_mask(  # Mask a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([[F, F, T], [F], [T, T]])).to_list()

[[3], [], [5, 6]]

# tf.RaggedTensor.from_row_lengths

In [7]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [8]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]).to_list())

[[3, 1, 4, 1], [], [5, 9, 2], [6], []]


# tf.RaggedTensor.from_row_limits

In [9]:
print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [10]:
print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8]).to_list())

[[3, 1, 4, 1], [], [5, 9, 2], [6], []]


# tf.RaggedTensor.from_row_starts

In [11]:
print(tf.RaggedTensor.from_row_starts(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_starts=[0, 4, 4, 7, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


# tf.RaggedTensor.from_tensor

In [12]:
dt = tf.constant([[5, 7, 0], [0, 3, 0], [6, 0, 0]])
tf.RaggedTensor.from_tensor(dt)

<tf.RaggedTensor [[5, 7, 0],
 [0, 3, 0],
 [6, 0, 0]]>

In [13]:
tf.RaggedTensor.from_tensor(dt, lengths=[1, 0, 3])

<tf.RaggedTensor [[5], [], [6, 0, 0]]>

# tf.sparse.SparseTensor

In [14]:
sparse_mat = tf.sparse.SparseTensor(indices=[[1,1],[3,4]], values=[12, 22], dense_shape=[10,11])
print(sparse_mat)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([12 22], shape=(2,), dtype=int32), dense_shape=tf.Tensor([10 11], shape=(2,), dtype=int64))


In [15]:
print(tf.sparse.to_dense(sparse_mat))

tf.Tensor(
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 22  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]], shape=(10, 11), dtype=int32)


# tf.strings.join

In [16]:
tf.strings.join(['abc','def']).numpy()

b'abcdef'

# tf.Variable

In [17]:
var = tf.Variable([[1.], [2.]])
print(var)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>


In [18]:
var[0].assign(20)
print(var)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[20.],
       [ 2.]], dtype=float32)>


In [19]:
c = tf.constant([1,2])
print(c)

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [20]:
c[0].assign(10)
print(c)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'